set :application, "csi"
set :user, "deploy"
set :repository,  "git@gluttony:csi.git"
set :deploy_to, "/var/www/apps/#{application}"

set :scm, :git
set :scm_username, user
set :runner, user

set :rails_env, 'production'

set :domain, "pride"
role :web, domain
role :app, domain
role :db,  domain, :primary => true

namespace :deploy do
  task :start do ; end
  task :stop do ; end
  task :restart, :roles => :app, :except => { :no_release => true } do
    run "#{try_sudo} touch #{File.join(current_path,'tmp','restart.txt')}"
  end
end

namespace :sass do
  desc 'Updates the stylesheets generated by Sass'
  task :update do
    invoke_command "cd #{latest_release}; RAILS_ENV=#{rails_env} rake sass:update"
  end

  before 'deploy:restart', 'sass:update'
end

namespace :fixtures do
  desc 'Loads default site fixtures'
  task :load_defaults do
    invoke_command "cd #{latest_release}; RAILS_ENV=#{rails_env} rake db:fixtures:load"
  end
  after 'deploy:start', 'fixtures:load_defaults'
end

namespace :db do
  desc 'Recreates server database'
  task :recreate do
    invoke_command "cd #{latest_release}; RAILS_ENV=#{rails_env} rake db:drop:all"
    invoke_command "cd #{latest_release}; RAILS_ENV=#{rails_env} rake db:create"
  end
end
